# galigo golangci-lint Configuration
# Tailored for Telegram Bot API library with strict quality standards

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: standard
  enable:
    # ====== Bug Detection (Critical) ======
    - bodyclose        # HTTP response body must be closed
    - contextcheck     # Non-inherited context detection
    - errcheck         # Unchecked errors (essential for API library)
    - errorlint        # Error wrapping issues (Go 1.13+)
    - govet            # Official Go vet checks
    - nilerr           # Returns nil when err != nil
    - staticcheck      # 150+ checks, gold standard

    # ====== Security ======
    - gosec            # Security vulnerability detection

    # ====== Performance ======
    - unconvert        # Unnecessary type conversions

    # ====== Code Quality ======
    - gocritic         # Extensive diagnostic checks
    - gocyclo          # Cyclomatic complexity
    - gocognit         # Cognitive complexity
    - unparam          # Unused function parameters
    - ineffassign      # Ineffective assignments

    # ====== Style & Formatting ======
    - misspell         # Spelling mistakes in comments
    - revive           # Modern golint replacement

    # ====== Go 1.25 Modern Linters ======
    - sloglint         # log/slog consistency (important for galigo)
    - intrange         # Use integer range loops where applicable

  disable:
    - prealloc         # Micro-optimization, adds noise without significant benefit

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false  # Allow explicit _ = for intentional ignores
      exclude-functions:
        - (*github.com/prilive-com/galigo/sender.Client).Close
        - io.Copy
        - io.WriteString
        - (net/http.ResponseWriter).Write  # HTTP writes rarely need checking

    govet:
      enable-all: true
      disable:
        - fieldalignment  # Not critical for API library

    gocyclo:
      min-complexity: 36  # Allow for LoadConfig (35) and BuildMultipartRequest (22)

    gocognit:
      min-complexity: 37  # Allow for LoadConfig env parsing (36)

    gosec:
      severity: medium
      confidence: medium
      excludes:
        - G104  # Unhandled errors (covered by errcheck)
        - G304  # File path from variable (needed for InputFile)
        - G306  # WriteFile permissions (0644 is fine for reports)
        - G301  # Directory permissions (0755 is fine for reports)
        - G404  # Weak random (acceptable in test code for delays)

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - whyNoLint         # Allow nolint without explanation in tests
        - hugeParam         # Request structs are intentionally passed by value (immutable)
        - paramTypeCombine  # Style preference, not a bug
        - exitAfterDefer    # Acceptable in CLI main() functions
        - rangeValCopy      # Acceptable for small iterations
        - ifElseChain       # Sometimes if-else is clearer than switch
        - unnamedResult     # Named returns optional for simple getters
        - redundantSprint   # fmt.Sprintf with single %s is explicit and clear

    revive:
      rules:
        - name: exported
          disabled: false
          arguments:
            - "checkPrivateReceivers"
        - name: var-naming
          disabled: false
          exclude:
            - "S[0-9]+_*"  # Allow S0_Smoke, S15_ChatInfo pattern for test scenarios
        - name: package-comments
          disabled: false

    sloglint:
      kv-only: false
      attr-only: false
      static-msg: false
      no-mixed-args: true
      no-global: "all"
      no-raw-keys: false

  exclusions:
    presets:
      - comments
      - std-error-handling

    paths:
      - cmd/galigo-testbot/fixtures
      - cmd/galigo-testbot/var

    rules:
      # Allow underscore naming in testbot suites (S0_Smoke, S15_ChatInfo, etc.)
      - path: cmd/galigo-testbot/suites/
        linters:
          - revive
        text: "var-naming.*underscore"

      # Allow longer functions and complexity in tests
      - path: _test\.go
        linters:
          - funlen
          - dupl
          - gosec
          - gocyclo
          - gocognit
          - errcheck      # Test code often intentionally ignores errors

      # Allow complexity in testbot
      - path: cmd/galigo-testbot/
        linters:
          - gocyclo
          - gocognit
          - funlen
          - gosec         # Test utilities don't need strict security
          - errcheck      # Test code often intentionally ignores errors

      # Allow complexity in internal test utilities
      - path: internal/testutil/
        linters:
          - errcheck
          - gosec

      # Allow unused parameters in interface implementations and callbacks
      - linters:
          - unparam
        text: "always receives"

      # Allow unused parameters in testbot CLI (flag callbacks, etc.)
      - path: cmd/galigo-testbot/
        linters:
          - unparam

      # Allow unused parameters in circuit breaker callbacks and similar
      - linters:
          - unparam
        text: "is unused"

      # Allow shadowing of common builtins in parameter names
      - linters:
          - gocritic
        text: "builtinShadow.*\\b(delete|min|max|cap)\\b"

      # Allow import shadowing for common patterns
      - linters:
          - gocritic
        text: "importShadow"

      # Allow httpNoBody suggestion (nil is idiomatic for GET requests)
      - linters:
          - gocritic
        text: "httpNoBody"

      # staticcheck: Allow embedded field access style
      - linters:
          - staticcheck
        text: "QF1008"

      # staticcheck: Allow if-else over tagged switch (sometimes clearer)
      - linters:
          - staticcheck
        text: "QF1003"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/prilive-com/galigo
