name: 🚀 Feature Request
description: Suggest a new feature or enhancement for galigo
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - sender (API calls)
        - receiver/polling (long polling)
        - receiver/webhook (webhook handling)
        - tg (types/errors)
        - Bot (unified interface)
        - New component
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Telegram Bot API method
        - New helper/utility
        - Performance improvement
        - Developer experience
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve. What are you trying to do that you can't do today?
      placeholder: I'm trying to... but galigo doesn't support...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution. How should this feature work?
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: API Design (Optional)
      description: If you have ideas for the API, please share them.
      placeholder: |
        ```go
        // Example of how you'd like to use this feature
        bot.NewMethod(ctx, params)
        ```

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references (e.g., Telegram Bot API docs).

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: This feature is related to the Telegram Bot API
          required: true
        - label: I am willing to help implement this feature
          required: false
